const CONSTANTS = {
  FILTERS_MARGIN: 5,
  FILTER_SECTION_HEIGHT: 65,
  PAINTING_SUBJECTS: [
    "AKT",
    "FIGURAL",
    "FLORA",
    "FAUNA",
    "LANDSCHAFT",
    "STILLEBEN",
    "STOCKERAU",
  ],
  PAINTING_TYPES: ["ACRYL", "AQUARELL", "KOHLE", "ÖL"],
};

export default CONSTANTS;
